### ISSUE TITLE
Scripts with multiple delimiters are ignored

### ISSUE THREAD

**Issue by zeke** [mysticatea/npm-run-all#106]
Given the following `package.json`:

```json
{
  "devDependencies": {
    "npm-run-all": "^4.0.2"
  },
  "scripts": {
    "build": "npm-run-all build:*",
    "build:mac": "echo mac",
    "build:mac:foo": "echo foo",
    "build:mac:bar": "echo bar"
  }
}
```

I would expect `npm run build` to output `mac`, `foo`, and `bar`. Instead:

```sh
$ npm run build

> @ build /Users/z/Desktop/demo
> npm-run-all build:*


> @ build:mac /Users/z/Desktop/demo
> echo mac

mac
```

If I change `build:mac:foo` to `build:mac-foo`, (replace the second colon with a dash), it runs as expected.

**Comment by mysticatea** [comment]
Thank you for this issue.

This is working as expected. `npm-run-all` is using glob-like pattern matching, but uses `:` as the delimiter instead of `/`. You can use global star `**` to run all sub-sub tasks.

See: https://github.com/mysticatea/npm-run-all/blob/master/docs/npm-run-all.md#glob-like-pattern-matching-for-script-names

**Comment by zeke** [comment]
Thanks, @mysticatea 👍
