### ISSUE TITLE
Setting env vars

### ISSUE THREAD

**Issue by juangl** [mysticatea/npm-run-all#64]
I love this feature in [better-npm-run](https://www.npmjs.com/package/better-npm-run). I'd like a way to define env vars before run a command and also it is cross platform.

**Comment by mysticatea** [comment]
Sorry, it's out of scope for this project.
[cross-env](https://www.npmjs.com/package/cross-env) is the tool to define environment variables in cross-platform.

I really hope that npm improves about the feature of environment variables.

**Comment by juangl** [comment]
Thank you for responce! I think it's a nice feature to add.

**Comment by jsonmaur** [comment]
@mysticatea At the very least, subprocesses should inherit the environment variables from the parent process. I find myself constantly wanting to do something like `NODE_ENV=testing npm-run-all test:*`. You wouldn't necessarily have to support cross-platform stuff, since that could easily be done by running `cross-env NODE_ENV=testing npm-run-all test:*`. npm-run-all should just send it's current env vars down to the sub-scripts.
