### ISSUE TITLE
Have to hit CTRL + c twice to kill run-all in terminal

### ISSUE THREAD

**Issue by wonbyte** [mysticatea/npm-run-all#74]
On macOS Sierra 10.12.1 when I use the npm-run-all in my start script I have to hit ctrl+c twice for it to kill the process. Would expect I can just hit ctrl+c once and that would kill the process.

**Comment by mysticatea** [comment]
Thank you for this issue, and I'm sorry that I delayed.

`npm-run-all` is not handling `SIGINT` signals.
The signals are supposed to send to child processes directly (and `npm-run-all` itself as well).
So some processes which are handling `SIGINT` signals might be in your npm-scripts.

**Comment by mysticatea** [comment]
At least, on Windows, `cmd.exe` needs `ctrl+c` twice to kill it.

**Comment by rizowski** [comment]
@mysticatea 
I am actually seeing this behavior as well. In my case this only seems to be caused with eslint-watch. If I remove eslint-watch it exits like normal. Problem being, I have verified that eslint-watch is exiting correctly so it seems like the parent process (npm-run-all) is not. Here is the issue that I have been trying to solve: https://github.com/rizowski/eslint-watch/issues/80

**Comment by jamietre** [comment]
So - I have spent some time dealing with the windows/CTRL+C issue and would like to help. There are actually other problems: in CMD shells CTRL+C will only kill the parent process. The child processes are detached and must be killed manually. I think most people use git bash, which may handle this better since it uses cygwin process model, but I use TCC/LE (a CMD replacement) and this comes up a lot. This is actually a bug with "npm run" itself, too.

So - I have made changes to npm-run-all in (my fork)[https://github.com/jamietre/npm-run-all] that solves this problem and ensures that CTRL+C will be trapped and correctly terminate the child processes. I would like to make a pull request, but I am concerned about the impact my changes would have on non-windows environments or possibly even uses cases other than my own basic one (starting parallel tasks from command line).

The specific thing I'm concerned about is that in order for this to work correctly in windows, `stdio` needs to be "inherit". I'm not very familiar with process spawning in *nix compared to linux - and I don't really understand the purpose of `detectStreamKind(stream, std)` in `lib/run-task.js`. So maybe this could just be coded to always use "inherit" for windows O/S, but I suspect there's more going on here (e.g. different invocation mechanisms? ) and I was hoping someone could explain this part of the code.

To sum up the changes generally:

The basic issue in windows is that there's no actual SIGINT signal. So when dealing with child processes, any code that depends on propagating SIGINT won't work. (This includes node spawn). In order to actually capture SIGINT you need to listen on stdin for a SIGINT, and then manually terminate child processes. So - while the shell might correctly terminate the outermost process when you hit CTRL+C, the SIGINT signal doesn't actually do anything when sent to child processes.

Additionally, it is possible for the child process itself to receive the CTRL+C signal rather than the parent process (and I don't unerstand exactly why this is, but it's easily reproducible) so you also need to handle possible user-initiated terminations of a child process and treat it differently from the process just ending normally or with an error (e.g. - always do an "abort")

**Comment by julmot** [comment]
For me, most of the time CTRL + C doesn't even work when calling it multiple times. Need to exit the CMD and reboot sometimes 👎

**Comment by stereokai** [comment]
CTRL+C doesn't work at all for me on Win 10

**Comment by cassiopagnoncelli** [comment]
Same problem on Mac OS high sierra. Capturing the signals and pass along to the children with 8s auto-exit timeout should solve.

**Comment by jbadlato** [comment]
Same problem for me using Git Bash/Windows 7.  CTRL+C doesn't abort the processes, and I have to manually end them in task manager.

**Comment by bobbwal** [comment]
Same for me too, Windows 10/Git bash, CTRL+C doesn't abort the processes and freezes up bash. Attempting to run browser-sync server and watch tasks, not sure if that is relevant.

**Comment by eduardoturconi** [comment]
For me, have to hit several times CTRL+C to kill the process.

**Comment by corysimmons** [comment]
Been a big proponent of npm-run-all for a long time but in https://github.com/begin-examples/node-create-react-app I have to _hold down_ ctrl + c to get it to eventually terminate. Switched to concurrently and it works fine. 🤷

**Comment by sahilrajput03** [comment]
I have use it for twice, but I'm happy with that. :D

**Comment by ghost** [comment]
I replaced the `start` script `run-p watch-ts watch-node` with `npm run watch-ts & npm run watch-node` to get proper SIGINT handling here:

```jsonc
{
  "scripts": {
    "prestart": "run-s clean build-ts",
    "start": "npm run watch-ts & npm run watch-node",
    "watch-node": "delay 1 && node --enable-source-maps --watch dist/index.js",
    "watch-ts": "tsc --watch",
    "win-start": "run-p watch-ts watch-node"
  }
}
```

It's not cross platform, but Windows devs can use the `win-start` script if they're not using bash.
