### ISSUE TITLE
Feature request: Variables

### ISSUE THREAD

**Issue by eirikb** [mysticatea/npm-run-all#89]
Would it be nice with variables?
This might be just silly, or somehow already supported, but in any case the idea would be to use something like this (_package.json_):

     {
      "npm-run-all": {
        "input": "not-mine/random-project-subfolder/which-for-unknown-reasons-is-located-here/src",
        "dist": "some-random-folder/output/dist"
      },
      "scripts": {
        "sass": "node-sass ${input}/css/styles.scss -o ${dist}",
        "postcss": "postcss ${dist}/styles.css -o ${dist}/styles-post.css"
      }
    }

The point is to remove input variables from the tasks. Values which might change, and might be repeated.

**Comment by mysticatea** [comment]
Thank you for this issue.

Granted, variables would be useful since environment variable's notation are different between platforms.
However, I don't think good if we write the scripts that `npm run-script` command cannot execute in the `scripts` field of `package.json`.

I recommend to use [the official `config` field of `package.json`](https://docs.npmjs.com/files/package.json#config) and [cross-conf-env](https://www.npmjs.com/package/cross-conf-env) module for cross-platform.

**Comment by eirikb** [comment]
I just realized that blunder as well, for this to work `npm-run-all` have to be the initiator, which would work, but it would render the `sass` and `postcss` tasks dependent on a `npm-run-all` task to start them (`npm run sass` wouldn't work).

Thanks for the answer! You are doing a great job with this lib, I use it all the time.
