### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by trevordmiller** [mysticatea/npm-run-all#9]
First off, awesome package! Great work. It has been very helpful so far as I am transitioning to using npm scripts instead of Gulp/Grunt. I'm just running into one issue: when I run my `npm run dev` script, which uses `npm-run-all` I get a `TypeError: undefined is not a function` error, which is preventing my `lint:watch` script from running. I have done some debugging, and everything works as expected running `npm run lint:watch` by itself, or `npm run dev` without the `lint:watch` command...but I don't know how to debug it. Is this a  known issue with `npm-run-all`?

## Related issue

I don't know if this is an issue with `eslint-watch` or `npm-run-all`, so I have posted the issue in both places. I do know that all of my other packages work as expected so something seems to be wrong with either `eslint-watch` or `npm-run-all`.

https://github.com/rizowski/eslint-watch/issues/28

## Steps to reproduce:

- Clone the project: https://github.com/trevordmiller/npm-run-all-example
- `npm install`
- `npm run lint:watch` runs as expected
- `npm run dev` runs `npm-run-all` which works for everything except for `lint:watch` which is outputting `TypeError: undefined is not a function`

![screen shot 2015-09-03 at 12 56 44 pm](https://cloud.githubusercontent.com/assets/5497885/9667798/4265d996-523b-11e5-8718-028df21e2e9b.png)

**Comment by mysticatea** [comment]
Thank you for the report!

I will dig this this evening (JST).

**Comment by mysticatea** [comment]
Sorry for my delay.
I published fixed version!

**Comment by trevordmiller** [comment]
@mysticatea Awesome. Thank you!

**Comment by tech-consortium** [comment]
@mysticatea Why if a variable is not set do you set it to undefined instead of just leaving it alone?   

For example, if we have these two scripts.

"cross-vars:echo": "cross-vars echo \"Node Environment = $node_env \\ NPM Production = $npm_config_production\"",

"cross-env:echo": "cross-env echo \"Node Environment = $node_env \\ NPM Production = $npm_config_production\"",

If NODE_ENV=production then both cross-env and cross-vars returns production.  But if NODE_ENV doesn't exist then that's where there is a difference.  With cross-env it just leaves it unset so there is no value in echo'd for node_env as we would expect. But with cross-vars it actually sets $NODE_ENV to "undefined".   Now imagine you were actually calling and angular build with a script like this...

"build": "cross-vars ng build --configuration=$node_env",

If $node_env isn't set to anything, then instead of $node_env being literally undefined or set to nothing, cross-vars is setting it to the actual string "undefined".  Having --configuration=undefined is going to cause the ng build to fail because there is no such thing as an "undefined" configuration environment.   Why don't you just leave the variable value alone if it's undefined?
