### ISSUE TITLE
bash: npm-run-all: command not found

### ISSUE THREAD

**Issue by shannonschaerer** [mysticatea/npm-run-all#96]
Am I missing something? I ran npm install npm-run-all --save-dev. I see it in package.json and in the node_modules folder, however I keep getting: 

> bash: npm-run-all: command not found

For example after running:

> npm-run-all -v

Is there anything else I need to do to get this running? Thanks in advance.

**Comment by mysticatea** [comment]
Thank for this issue.

This is `npm` matter.
There are 2 installation style, local and global, on `npm`.

In the global installation case, `npm-run-all` will be installed into the place which `PATH` environment variable includes. You can use `npm-run-all` everywhere, but you cannot use different versions for each project and it's relatively difficult that your team use the same version of `npm-run-all`.

In the local installation case which you did, `npm-run-all` will be installed into the your project's `node_modules` directory. `PATH` environment variable does not include there, so you have to use `./node_modules/.bin/npm-run-all` (or `$(npm bin)/npm-run-all`) to run `npm-run-all`. But you can use different versions of `npm-run-all` for each project and your team can use the same version of `npm-run-all` easily via `package.json`. And you can use `npm-run-all` command in npm-scripts even if it's local installed because `npm` adds `./node_modules/.bin` to `PATH` before `npm run-script` command.

See also: https://docs.npmjs.com/

**Comment by shannonschaerer** [comment]
I forgot that sometimes I need to be more explicit. Duh! Thanks for your help!

**Comment by MB-Hilo** [comment]
you can use "npx npm-run-all yourscript"  as well

**Comment by brettz9** [comment]
I don't have a global installation and was only using via npm script, but I somehow got this error.

I was able to fix though by removing `node_modules`/`package-lock.json` and installing again.

Such a useful package--should be built-in to npm!
